import { SensorNode, Pillar, CoalfieldZone, Alert } from '../types';

export const THRESHOLDS = {
  strain: {
    warning: 350,   // microstrain (µε)
    critical: 600,
    unit: 'µε',
  },
  tilt: {
    warning: 1.5,   // degrees (°)
    critical: 3.0,
    unit: '°',
  },
  geophone: {
    warning: 5.0,   // mm/s Peak Particle Velocity
    critical: 12.0,
    unit: 'mm/s',
  },
  risk: {
    caution: 35,
    critical: 70,
  }
};

export const COALFIELD_ZONES: CoalfieldZone[] = [
  {
    id: 'jharia-block-4',
    name: 'Jharia Colliery — Block IV',
    basin: 'Damodar Valley Basin',
    state: 'Jharkhand',
    lat: 23.7423,
    lng: 86.4189,
    strataType: 'Barakar Sandstone / Coal Seam XII',
    activeNodes: 12,
    currentRiskScore: 24,
    insarDeformationRateMmYr: -14.2, // mm/year subsidence velocity from Sentinel-1 SBAS
  },
  {
    id: 'raniganj-sector-2',
    name: 'Raniganj Colliery — Sector 2',
    basin: 'Raniganj Coal Basin',
    state: 'West Bengal',
    lat: 23.6186,
    lng: 86.9744,
    strataType: 'Dishergarh Seam / Shale Overburden',
    activeNodes: 10,
    currentRiskScore: 18,
    insarDeformationRateMmYr: -8.6,
  }
];

export const INITIAL_SENSOR_NODES: SensorNode[] = [
  {
    id: 'NODE-TM-01',
    name: 'Roof Tiltmeter TM-01',
    type: 'tiltmeter',
    unit: '°',
    location: 'Gallery 4-East, Seam XII',
    depthMeters: 245,
    currentValue: 0.34,
    baselineValue: 0.30,
    warningThreshold: 1.5,
    criticalThreshold: 3.0,
    status: 'normal',
    batteryPercent: 94,
    signalDbm: -68,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
  },
  {
    id: 'NODE-TM-02',
    name: 'Barrier Tiltmeter TM-02',
    type: 'tiltmeter',
    unit: '°',
    location: 'Pillar P-06 Flank, Seam XII',
    depthMeters: 250,
    currentValue: 0.42,
    baselineValue: 0.38,
    warningThreshold: 1.5,
    criticalThreshold: 3.0,
    status: 'normal',
    batteryPercent: 88,
    signalDbm: -72,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
  },
  {
    id: 'NODE-SG-01',
    name: 'Vibrating Wire Strain SG-01',
    type: 'strain_gauge',
    unit: 'µε',
    location: 'Pillar P-05 Core',
    depthMeters: 248,
    currentValue: 142.5,
    baselineValue: 135.0,
    warningThreshold: 350.0,
    criticalThreshold: 600.0,
    status: 'normal',
    batteryPercent: 91,
    signalDbm: -65,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
  },
  {
    id: 'NODE-SG-02',
    name: 'Pillar Rib Strain SG-02',
    type: 'strain_gauge',
    unit: 'µε',
    location: 'Pillar P-07 Haulage Line',
    depthMeters: 252,
    currentValue: 168.2,
    baselineValue: 155.0,
    warningThreshold: 350.0,
    criticalThreshold: 600.0,
    status: 'normal',
    batteryPercent: 86,
    signalDbm: -75,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
  },
  {
    id: 'NODE-SG-03',
    name: 'Goaf Perimeter Strain SG-03',
    type: 'strain_gauge',
    unit: 'µε',
    location: 'Boundary Barrier North',
    depthMeters: 240,
    currentValue: 115.0,
    baselineValue: 110.0,
    warningThreshold: 350.0,
    criticalThreshold: 600.0,
    status: 'normal',
    batteryPercent: 96,
    signalDbm: -62,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
  },
  {
    id: 'NODE-GP-01',
    name: 'Tri-axial Geophone GP-01',
    type: 'geophone',
    unit: 'mm/s',
    location: 'Sub-surface Drift Chamber',
    depthMeters: 190,
    currentValue: 0.18,
    baselineValue: 0.12,
    warningThreshold: 5.0,
    criticalThreshold: 12.0,
    status: 'normal',
    batteryPercent: 98,
    signalDbm: -58,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
  },
  {
    id: 'NODE-GP-02',
    name: 'High-Frequency Geophone GP-02',
    type: 'geophone',
    unit: 'mm/s',
    location: 'Pillar P-10 Deep Winze',
    depthMeters: 260,
    currentValue: 0.24,
    baselineValue: 0.15,
    warningThreshold: 5.0,
    criticalThreshold: 12.0,
    status: 'normal',
    batteryPercent: 82,
    signalDbm: -79,
    zigbeeHops: 3,
    lastUpdated: 'Just now',
  },
  {
    id: 'NODE-TM-03',
    name: 'Main Dip Tiltmeter TM-03',
    type: 'tiltmeter',
    unit: '°',
    location: 'Conveyor Trunk Line',
    depthMeters: 230,
    currentValue: 0.28,
    baselineValue: 0.25,
    warningThreshold: 1.5,
    criticalThreshold: 3.0,
    status: 'normal',
    batteryPercent: 93,
    signalDbm: -60,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
  },
];

export const INITIAL_PILLARS: Pillar[] = [
  { id: 'P-01', name: 'Pillar 01 (Shaft Pillar)', gridPos: [0, 0], depthMeters: 240, factorOfSafety: 2.35, stressMpa: 13.8, strainMicrostrain: 128, status: 'stable', displacementMm: 1.2 },
  { id: 'P-02', name: 'Pillar 02 (Main Intake)', gridPos: [0, 1], depthMeters: 242, factorOfSafety: 2.28, stressMpa: 14.5, strainMicrostrain: 135, status: 'stable', displacementMm: 1.4 },
  { id: 'P-03', name: 'Pillar 03 (Haulage Way)', gridPos: [0, 2], depthMeters: 244, factorOfSafety: 2.15, stressMpa: 15.2, strainMicrostrain: 148, status: 'stable', displacementMm: 1.7 },
  { id: 'P-04', name: 'Pillar 04 (Return Airway)', gridPos: [0, 3], depthMeters: 245, factorOfSafety: 2.20, stressMpa: 14.9, strainMicrostrain: 142, status: 'stable', displacementMm: 1.5 },
  
  { id: 'P-05', name: 'Pillar 05 (Junction 2)', gridPos: [1, 0], depthMeters: 246, factorOfSafety: 2.10, stressMpa: 15.8, strainMicrostrain: 162, status: 'stable', displacementMm: 1.9 },
  { id: 'P-06', name: 'Pillar 06 (Critical Rib)', gridPos: [1, 1], depthMeters: 248, factorOfSafety: 1.88, stressMpa: 18.2, strainMicrostrain: 210, status: 'stressed', displacementMm: 2.8 },
  { id: 'P-07', name: 'Pillar 07 (Central Panel)', gridPos: [1, 2], depthMeters: 250, factorOfSafety: 1.92, stressMpa: 17.6, strainMicrostrain: 198, status: 'stable', displacementMm: 2.4 },
  { id: 'P-08', name: 'Pillar 08 (East Flank)', gridPos: [1, 3], depthMeters: 251, factorOfSafety: 2.22, stressMpa: 14.8, strainMicrostrain: 140, status: 'stable', displacementMm: 1.6 },
  
  { id: 'P-09', name: 'Pillar 09 (Goaf Barrier)', gridPos: [2, 0], depthMeters: 252, factorOfSafety: 2.05, stressMpa: 16.4, strainMicrostrain: 174, status: 'stable', displacementMm: 2.1 },
  { id: 'P-10', name: 'Pillar 10 (Deep Winze)', gridPos: [2, 1], depthMeters: 255, factorOfSafety: 1.85, stressMpa: 18.9, strainMicrostrain: 228, status: 'stressed', displacementMm: 3.1 },
  { id: 'P-11', name: 'Pillar 11 (Depillaring Zone)', gridPos: [2, 2], depthMeters: 256, factorOfSafety: 1.76, stressMpa: 19.8, strainMicrostrain: 245, status: 'stressed', displacementMm: 3.5 },
  { id: 'P-12', name: 'Pillar 12 (Substation)', gridPos: [2, 3], depthMeters: 254, factorOfSafety: 2.30, stressMpa: 14.0, strainMicrostrain: 130, status: 'stable', displacementMm: 1.3 },
  
  { id: 'P-13', name: 'Pillar 13 (South Barrier)', gridPos: [3, 0], depthMeters: 258, factorOfSafety: 2.40, stressMpa: 13.2, strainMicrostrain: 120, status: 'stable', displacementMm: 1.1 },
  { id: 'P-14', name: 'Pillar 14 (Tailgate Dip)', gridPos: [3, 1], depthMeters: 260, factorOfSafety: 2.18, stressMpa: 15.3, strainMicrostrain: 150, status: 'stable', displacementMm: 1.8 },
  { id: 'P-15', name: 'Pillar 15 (Sump Chamber)', gridPos: [3, 2], depthMeters: 262, factorOfSafety: 2.25, stressMpa: 14.6, strainMicrostrain: 138, status: 'stable', displacementMm: 1.5 },
  { id: 'P-16', name: 'Pillar 16 (Boundary Wall)', gridPos: [3, 3], depthMeters: 260, factorOfSafety: 2.38, stressMpa: 13.5, strainMicrostrain: 125, status: 'stable', displacementMm: 1.2 },
];

export const INITIAL_ALERTS: Alert[] = [
  {
    id: 'ALT-1049',
    timestamp: '10 mins ago',
    title: 'Baseline Mesh Sync Completed',
    message: '12 Zigbee nodes verified via LoRa Gateway LOR-JH-01. Hop latency < 140ms.',
    severity: 'info',
    coalfield: 'Jharia Colliery — Block IV',
    acknowledged: true,
    dgmsCode: 'DGMS/TECH/CIRC-04',
  },
  {
    id: 'ALT-1048',
    timestamp: '32 mins ago',
    title: 'Micro-seismic Tremor Registered',
    message: 'Geophone GP-02 recorded transient vibration peak of 0.85 mm/s. Well below 5.0 mm/s limit.',
    severity: 'info',
    nodeId: 'NODE-GP-02',
    coalfield: 'Jharia Colliery — Block IV',
    acknowledged: true,
    dgmsCode: 'DGMS/S&T/CMR-111',
  },
  {
    id: 'ALT-1047',
    timestamp: '2 hours ago',
    title: 'Minor Microstrain Drift on Pillar P-11',
    message: 'Strain increased by +18 µε during blasting in adjacent seam. Normal stress redistribution.',
    severity: 'info',
    nodeId: 'NODE-SG-02',
    coalfield: 'Jharia Colliery — Block IV',
    acknowledged: true,
    dgmsCode: 'DGMS/SAFE/REC-19',
  }
];
