import { SensorNode, Pillar, CoalfieldZone, Alert } from '../types';

export const SURFACE_THRESHOLDS = {
  linearPotDisplacement: {
    warning: 10.0,  // mm ground subsidence
    critical: 25.0, // mm ground subsidence
    unit: 'mm',
    maxStroke: 50.0,
  },
  linearPotCrack: {
    warning: 8.0,   // mm fissure opening
    critical: 20.0,
    unit: 'mm',
    maxStroke: 100.0,
  },
  surfaceTilt: {
    warning: 0.80,  // degrees
    critical: 1.80,
    unit: '°',
  },
  surfaceVibration: {
    warning: 2.50,  // mm/s Peak Particle Velocity
    critical: 6.00,
    unit: 'mm/s',
  },
};

export const UNDERGROUND_THRESHOLDS = {
  bf350Strain: {
    warning: 350.0, // microstrain (µε)
    critical: 600.0,
    unit: 'µε',
  },
  undergroundTilt: {
    warning: 1.50,  // degrees
    critical: 3.00,
    unit: '°',
  },
  undergroundVibration: {
    warning: 5.00,  // mm/s PPV
    critical: 12.00,
    unit: 'mm/s',
  },
  mq4Methane: {
    warning: 0.80,  // % LEL
    critical: 1.25, // % LEL (DGMS Statutory CMR-111 / Reg 169 Cap)
    unit: '% LEL',
  },
  convergence: {
    warning: 15.0,  // mm
    critical: 30.0,
    unit: 'mm',
  }
};

export const THRESHOLDS = {
  strain: {
    warning: 350,
    critical: 600,
    unit: 'µε',
  },
  tilt: {
    warning: 1.5,
    critical: 3.0,
    unit: '°',
  },
  geophone: {
    warning: 5.0,
    critical: 12.0,
    unit: 'mm/s',
  },
  risk: {
    caution: 35,
    critical: 70,
  }
};

export const COALFIELD_ZONES: CoalfieldZone[] = [
  {
    id: 'jharia-block-4',
    name: 'Jharia Colliery — Block IV',
    basin: 'Damodar Valley Basin',
    state: 'Jharkhand',
    lat: 23.7423,
    lng: 86.4189,
    strataType: 'Barakar Sandstone / Coal Seam XII',
    activeNodes: 32,
    currentRiskScore: 24,
    insarDeformationRateMmYr: -14.2, // mm/year subsidence velocity from Sentinel-1 SBAS
    isPrimaryFocus: true,
    productionCapacityMtpa: 4.8,
    depthMeters: 248,
  },
  {
    id: 'karanpura-block-1',
    name: 'Karanpura Coalfields — Jharkhand',
    basin: 'Damodar Valley / Karanpura Basin',
    state: 'Jharkhand',
    lat: 23.8512,
    lng: 85.2845,
    strataType: 'Barakar / Karharbari Formation',
    activeNodes: 14,
    currentRiskScore: 16,
    insarDeformationRateMmYr: -6.4,
    isPrimaryFocus: false,
    productionCapacityMtpa: 3.2,
    depthMeters: 195,
  },
  {
    id: 'korba-secl',
    name: 'Korba Coalfield — Chhattisgarh',
    basin: 'Hasdeo River Basin (SECL)',
    state: 'Chhattisgarh',
    lat: 22.3595,
    lng: 82.7501,
    strataType: 'Upper & Lower Kusmunda Seam / Sandstone',
    activeNodes: 16,
    currentRiskScore: 14,
    insarDeformationRateMmYr: -5.2,
    isPrimaryFocus: false,
    productionCapacityMtpa: 6.5,
    depthMeters: 160,
  },
  {
    id: 'raniganj-sector-2',
    name: 'Raniganj Colliery — Sector 2',
    basin: 'Raniganj Coal Basin / Damodar East',
    state: 'West Bengal',
    lat: 23.6186,
    lng: 86.9744,
    strataType: 'Dishergarh Seam / Shale Overburden',
    activeNodes: 20,
    currentRiskScore: 18,
    insarDeformationRateMmYr: -8.6,
    isPrimaryFocus: false,
    productionCapacityMtpa: 2.4,
    depthMeters: 210,
  }
];

export const INITIAL_SENSOR_NODES: SensorNode[] = [
  // ==========================================
  // ABOVE THE SURFACE FLEET (Station SF-01/SF-02)
  // ==========================================
  {
    id: 'NODE-SF-POT-01',
    name: 'Surface Subsidence Potentiometer POT-01',
    hardwareModel: 'Linear Potentiometer 50mm Travel (Slide Pot)',
    domain: 'surface',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Pithead Subsidence Monument SF-01',
    depthMeters: 0,
    currentValue: 1.25,
    baselineValue: 1.20,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 97,
    signalDbm: -54,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    rawSignal: 'ADC 12-bit: 102/4095 (0.082V)',
  },
  {
    id: 'NODE-SF-MPU-01',
    name: 'Surface Slope Inclinometer MPU-01',
    hardwareModel: 'MPU-6050 6-Axis IMU (I2C 0x68)',
    domain: 'surface',
    type: 'mpu6050_tilt',
    unit: '°',
    location: 'Ground Monument Station SF-01',
    depthMeters: 0,
    currentValue: 0.14,
    baselineValue: 0.12,
    warningThreshold: 0.80,
    criticalThreshold: 1.80,
    status: 'normal',
    batteryPercent: 95,
    signalDbm: -56,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    rawSignal: 'Pitch: +0.14° | Roll: -0.06°',
  },
  {
    id: 'NODE-SF-MPU-02',
    name: 'Surface Ground Vibration MPU-02',
    hardwareModel: 'MPU-6050 6-Axis IMU (I2C 0x69)',
    domain: 'surface',
    type: 'mpu6050_vib',
    unit: 'mm/s',
    location: 'Perimeter Surface Array SF-02',
    depthMeters: 0,
    currentValue: 0.08,
    baselineValue: 0.05,
    warningThreshold: 2.50,
    criticalThreshold: 6.00,
    status: 'normal',
    batteryPercent: 91,
    signalDbm: -63,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    rawSignal: 'RMS Accel: 0.008g (PPV: 0.08 mm/s)',
  },

  // ==========================================
  // UNDERGROUND STRATA FLEET (Seam XII -248m RL)
  // ==========================================
  {
    id: 'NODE-UG-BF350-01',
    name: 'Pillar Core Strain Gauge BF350-01',
    hardwareModel: 'BF350 Strain Gauge + HX711 24-bit ADC Amplifier',
    domain: 'underground',
    type: 'bf350_strain',
    unit: 'µε',
    location: 'Pillar P-06 Core, Seam XII',
    depthMeters: 248,
    currentValue: 142.5,
    baselineValue: 135.0,
    warningThreshold: 350.0,
    criticalThreshold: 600.0,
    status: 'normal',
    batteryPercent: 92,
    signalDbm: -68,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    rawSignal: 'HX711 24-bit: 2,992,500 counts (21.0 c/µε)',
  },
  {
    id: 'NODE-UG-BF350-02',
    name: 'Depillaring Flank Strain BF350-02',
    hardwareModel: 'BF350 Strain Gauge + HX711 24-bit ADC Amplifier',
    domain: 'underground',
    type: 'bf350_strain',
    unit: 'µε',
    location: 'Pillar P-11 Rib, Extraction Face',
    depthMeters: 256,
    currentValue: 168.2,
    baselineValue: 155.0,
    warningThreshold: 350.0,
    criticalThreshold: 600.0,
    status: 'normal',
    batteryPercent: 88,
    signalDbm: -74,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    rawSignal: 'HX711 24-bit: 3,532,200 counts (21.0 c/µε)',
  },
  {
    id: 'NODE-UG-MPU-01',
    name: 'Roof Strata Inclinometer MPU-01',
    hardwareModel: 'MPU-6050 6-Axis IMU (Subterranean Ex-ia)',
    domain: 'underground',
    type: 'mpu6050_tilt',
    unit: '°',
    location: 'Gallery 4-East Roof Anchor, Seam XII',
    depthMeters: 245,
    currentValue: 0.36,
    baselineValue: 0.30,
    warningThreshold: 1.50,
    criticalThreshold: 3.00,
    status: 'normal',
    batteryPercent: 94,
    signalDbm: -66,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    rawSignal: 'Roof Delamination Pitch: +0.36°',
  },
  {
    id: 'NODE-UG-MPU-02',
    name: 'Strata Shock Vibration MPU-02',
    hardwareModel: 'MPU-6050 6-Axis IMU (Dynamic Geophone Proxy)',
    domain: 'underground',
    type: 'mpu6050_vib',
    unit: 'mm/s',
    location: 'Pillar P-10 Deep Winze Chamber',
    depthMeters: 260,
    currentValue: 0.22,
    baselineValue: 0.15,
    warningThreshold: 5.00,
    criticalThreshold: 12.00,
    status: 'normal',
    batteryPercent: 84,
    signalDbm: -78,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    rawSignal: 'PPV Peak: 0.22 mm/s @ 32Hz',
  },
  {
    id: 'NODE-UG-MQ4-01',
    name: 'Tailgate Methane Gas Sensor MQ4-01',
    hardwareModel: 'MQ-4 Catalytic Methane (CH4) Sensor',
    domain: 'underground',
    type: 'mq4_gas',
    unit: '% LEL',
    location: 'Tailgate Return Airway, Seam XII',
    depthMeters: 252,
    currentValue: 0.22,
    baselineValue: 0.15,
    warningThreshold: 0.80,
    criticalThreshold: 1.25,
    status: 'normal',
    batteryPercent: 90,
    signalDbm: -70,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    rawSignal: 'Analog Rs/Ro: 14.8kΩ (~110 ppm CH4)',
  },
  {
    id: 'NODE-UG-MQ4-02',
    name: 'Goaf Perimeter Methane MQ4-02',
    hardwareModel: 'MQ-4 Catalytic Methane (CH4) Sensor',
    domain: 'underground',
    type: 'mq4_gas',
    unit: '% LEL',
    location: 'Goaf Bleeder Channel North',
    depthMeters: 240,
    currentValue: 0.28,
    baselineValue: 0.20,
    warningThreshold: 0.80,
    criticalThreshold: 1.25,
    status: 'normal',
    batteryPercent: 96,
    signalDbm: -62,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    rawSignal: 'Analog Rs/Ro: 12.2kΩ (~140 ppm CH4)',
  },
];

export const INITIAL_PILLARS: Pillar[] = [
  { id: 'P-01', name: 'Pillar 01 (Shaft Pillar)', gridPos: [0, 0], depthMeters: 240, factorOfSafety: 2.35, stressMpa: 13.8, strainMicrostrain: 128, status: 'stable', displacementMm: 1.2 },
  { id: 'P-02', name: 'Pillar 02 (Main Intake)', gridPos: [0, 1], depthMeters: 242, factorOfSafety: 2.28, stressMpa: 14.5, strainMicrostrain: 135, status: 'stable', displacementMm: 1.4 },
  { id: 'P-03', name: 'Pillar 03 (Haulage Way)', gridPos: [0, 2], depthMeters: 244, factorOfSafety: 2.15, stressMpa: 15.2, strainMicrostrain: 148, status: 'stable', displacementMm: 1.7 },
  { id: 'P-04', name: 'Pillar 04 (Return Airway)', gridPos: [0, 3], depthMeters: 245, factorOfSafety: 2.20, stressMpa: 14.9, strainMicrostrain: 142, status: 'stable', displacementMm: 1.5 },
  
  { id: 'P-05', name: 'Pillar 05 (Junction 2)', gridPos: [1, 0], depthMeters: 246, factorOfSafety: 2.10, stressMpa: 15.8, strainMicrostrain: 162, status: 'stable', displacementMm: 1.9 },
  { id: 'P-06', name: 'Pillar 06 (Critical Rib)', gridPos: [1, 1], depthMeters: 248, factorOfSafety: 1.88, stressMpa: 18.2, strainMicrostrain: 210, status: 'stressed', displacementMm: 2.8 },
  { id: 'P-07', name: 'Pillar 07 (Central Panel)', gridPos: [1, 2], depthMeters: 250, factorOfSafety: 1.92, stressMpa: 17.6, strainMicrostrain: 198, status: 'stable', displacementMm: 2.4 },
  { id: 'P-08', name: 'Pillar 08 (East Flank)', gridPos: [1, 3], depthMeters: 251, factorOfSafety: 2.22, stressMpa: 14.8, strainMicrostrain: 140, status: 'stable', displacementMm: 1.6 },
  
  { id: 'P-09', name: 'Pillar 09 (Goaf Barrier)', gridPos: [2, 0], depthMeters: 252, factorOfSafety: 2.05, stressMpa: 16.4, strainMicrostrain: 174, status: 'stable', displacementMm: 2.1 },
  { id: 'P-10', name: 'Pillar 10 (Deep Winze)', gridPos: [2, 1], depthMeters: 255, factorOfSafety: 1.85, stressMpa: 18.9, strainMicrostrain: 228, status: 'stressed', displacementMm: 3.1 },
  { id: 'P-11', name: 'Pillar 11 (Depillaring Zone)', gridPos: [2, 2], depthMeters: 256, factorOfSafety: 1.76, stressMpa: 19.8, strainMicrostrain: 245, status: 'stressed', displacementMm: 3.5 },
  { id: 'P-12', name: 'Pillar 12 (Substation)', gridPos: [2, 3], depthMeters: 254, factorOfSafety: 2.30, stressMpa: 14.0, strainMicrostrain: 130, status: 'stable', displacementMm: 1.3 },
  
  { id: 'P-13', name: 'Pillar 13 (South Barrier)', gridPos: [3, 0], depthMeters: 258, factorOfSafety: 2.40, stressMpa: 13.2, strainMicrostrain: 120, status: 'stable', displacementMm: 1.1 },
  { id: 'P-14', name: 'Pillar 14 (Tailgate Dip)', gridPos: [3, 1], depthMeters: 260, factorOfSafety: 2.18, stressMpa: 15.3, strainMicrostrain: 150, status: 'stable', displacementMm: 1.8 },
  { id: 'P-15', name: 'Pillar 15 (Sump Chamber)', gridPos: [3, 2], depthMeters: 262, factorOfSafety: 2.25, stressMpa: 14.6, strainMicrostrain: 138, status: 'stable', displacementMm: 1.5 },
  { id: 'P-16', name: 'Pillar 16 (Boundary Wall)', gridPos: [3, 3], depthMeters: 260, factorOfSafety: 2.38, stressMpa: 13.5, strainMicrostrain: 125, status: 'stable', displacementMm: 1.2 },
];

export const INITIAL_ALERTS: Alert[] = [
  {
    id: 'ALT-1049',
    timestamp: '10 mins ago',
    title: 'Baseline Mesh Sync Completed',
    message: '12 Zigbee nodes verified via LoRa Gateway LOR-JH-01. Hop latency < 140ms.',
    severity: 'info',
    coalfield: 'Jharia Colliery — Block IV',
    acknowledged: true,
    dgmsCode: 'DGMS/TECH/CIRC-04',
  },
  {
    id: 'ALT-1048',
    timestamp: '32 mins ago',
    title: 'Micro-seismic Tremor Registered',
    message: 'Geophone GP-02 recorded transient vibration peak of 0.85 mm/s. Well below 5.0 mm/s limit.',
    severity: 'info',
    nodeId: 'NODE-GP-02',
    coalfield: 'Jharia Colliery — Block IV',
    acknowledged: true,
    dgmsCode: 'DGMS/S&T/CMR-111',
  },
  {
    id: 'ALT-1047',
    timestamp: '2 hours ago',
    title: 'Minor Microstrain Drift on Pillar P-11',
    message: 'Strain increased by +18 µε during blasting in adjacent seam. Normal stress redistribution.',
    severity: 'info',
    nodeId: 'NODE-SG-02',
    coalfield: 'Jharia Colliery — Block IV',
    acknowledged: true,
    dgmsCode: 'DGMS/SAFE/REC-19',
  }
];

// =============================================================================
// RANIGANJ COLLIERY (SECTOR 2) — DEDICATED 20-NODE SENSOR FLEET
// =============================================================================
export const RANIGANJ_SENSOR_NODES: SensorNode[] = [
  // --- 1. Multi-Point Borehole Extensometers (6 nodes) ---
  {
    id: 'NODE-RAN-EXT-01',
    name: 'Dishergarh Headgate MPBX-01',
    hardwareModel: 'Multi-Point Borehole Extensometer (4-Anchor LVDT)',
    domain: 'underground',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Panel D-1 Headgate (-210m RL)',
    depthMeters: 210,
    currentValue: 2.14,
    baselineValue: 1.80,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 94,
    signalDbm: -62,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    rawSignal: 'Anchor 1: +2.14mm | Anchor 2: +1.10mm | Anchor 3: +0.40mm',
    lat: 23.6215,
    lng: 86.9712,
  },
  {
    id: 'NODE-RAN-EXT-02',
    name: 'Dishergarh Tailgate MPBX-02',
    hardwareModel: 'Multi-Point Borehole Extensometer (4-Anchor LVDT)',
    domain: 'underground',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Panel D-2 Tailgate Return (-215m RL)',
    depthMeters: 215,
    currentValue: 3.42,
    baselineValue: 2.90,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 89,
    signalDbm: -69,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    rawSignal: 'Anchor 1: +3.42mm | Anchor 2: +1.95mm | Anchor 3: +0.82mm',
    lat: 23.6158,
    lng: 86.9782,
  },
  {
    id: 'NODE-RAN-EXT-03',
    name: 'Sitarampur Overburden MPBX-03',
    hardwareModel: 'Deep Borehole Cable Extensometer',
    domain: 'surface',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Sitarampur Mid-Horizon Borehole BH-14',
    depthMeters: 85,
    currentValue: 1.65,
    baselineValue: 1.50,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 96,
    signalDbm: -58,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    rawSignal: 'Sandstone Shear Dislocation: +1.65mm',
    lat: 23.6242,
    lng: 86.9685,
  },
  {
    id: 'NODE-RAN-EXT-04',
    name: 'Railway Protection Barrier MPBX-04',
    hardwareModel: 'Linear Ground Displacement Potentiometer',
    domain: 'surface',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Eastern Railway Main Line Corridor Boundary',
    depthMeters: 0,
    currentValue: 0.85,
    baselineValue: 0.80,
    warningThreshold: 8.0,
    criticalThreshold: 18.0,
    status: 'normal',
    batteryPercent: 98,
    signalDbm: -51,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    rawSignal: 'Surface Rail Bed Heave/Settlement: +0.85mm',
    lat: 23.6268,
    lng: 86.9805,
  },
  {
    id: 'NODE-RAN-EXT-05',
    name: 'Damodar Alluvium Settlement MPBX-05',
    hardwareModel: 'Multi-Anchor Hydraulic Extensometer',
    domain: 'surface',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Damodar South Embankment Pier Pier-3',
    depthMeters: 18,
    currentValue: 1.92,
    baselineValue: 1.85,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 92,
    signalDbm: -65,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    rawSignal: 'Alluvium Compaction: +1.92mm',
    lat: 23.6105,
    lng: 86.9715,
  },
  {
    id: 'NODE-RAN-EXT-06',
    name: 'Goaf Caving Wire Extensometer MPBX-06',
    hardwareModel: 'Sub-Level Multi-Wire Dislocation Gauge',
    domain: 'underground',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Panel D-1 Goaf Overburden Barrier',
    depthMeters: 180,
    currentValue: 4.10,
    baselineValue: 3.50,
    warningThreshold: 12.0,
    criticalThreshold: 30.0,
    status: 'normal',
    batteryPercent: 86,
    signalDbm: -72,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    rawSignal: 'Roof Span Sag: 4.10mm',
    lat: 23.6198,
    lng: 86.9642,
  },

  // --- 2. High-Precision GNSS / InSAR Radar Reflectors (4 nodes) ---
  {
    id: 'NODE-RAN-GNSS-01',
    name: 'Raniganj Sector 2 Base GNSS RS-01',
    hardwareModel: 'Leica GMX910 Multi-GNSS Geodetic Receiver',
    domain: 'surface',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Sector 2 Colliery Office Roof Station',
    depthMeters: 0,
    currentValue: 1.12,
    baselineValue: 1.10,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 99,
    signalDbm: -48,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    rawSignal: 'PPP-RTK 3D RMS: 0.8mm (Fixed Solution)',
    lat: 23.6186,
    lng: 86.9744,
  },
  {
    id: 'NODE-RAN-GNSS-02',
    name: 'InSAR Corner Reflector CCR-01',
    hardwareModel: '1.2m Triangular Corner Cube InSAR Transponder',
    domain: 'surface',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Sitarampur Overburden Bench North',
    depthMeters: 0,
    currentValue: 2.85,
    baselineValue: 2.70,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 97,
    signalDbm: -53,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    rawSignal: 'Sentinel-1 Line-of-Sight LOS Phase Shift: -2.85mm',
    lat: 23.6252,
    lng: 86.9731,
  },
  {
    id: 'NODE-RAN-GNSS-03',
    name: 'InSAR Corner Reflector CCR-02',
    hardwareModel: '1.2m Triangular Corner Cube InSAR Transponder',
    domain: 'surface',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Damodar North Floodplain Dyke',
    depthMeters: 0,
    currentValue: 1.45,
    baselineValue: 1.40,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 95,
    signalDbm: -59,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    rawSignal: 'Sentinel-1 Descending Pass: -1.45mm LOS',
    lat: 23.6128,
    lng: 86.9680,
  },
  {
    id: 'NODE-RAN-GNSS-04',
    name: 'East Perimeter GNSS Station RS-02',
    hardwareModel: 'Continuous Dual-Frequency GNSS Sensor',
    domain: 'surface',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Raniganj Eastern Boundary Monument SF-03',
    depthMeters: 0,
    currentValue: 0.90,
    baselineValue: 0.85,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 96,
    signalDbm: -55,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    rawSignal: 'RTK Elevation Deviation: +0.90mm',
    lat: 23.6210,
    lng: 86.9840,
  },

  // --- 3. Damodar River Embankment Aquifer Tiltmeters (4 nodes) ---
  {
    id: 'NODE-RAN-TILT-01',
    name: 'River Embankment Inclinometer TILT-01',
    hardwareModel: 'Biaxial MEMS Inclinometer (IP68 Submersible)',
    domain: 'surface',
    type: 'mpu6050_tilt',
    unit: '°',
    location: 'Damodar Right Bank Levee Top (East)',
    depthMeters: 0,
    currentValue: 0.18,
    baselineValue: 0.15,
    warningThreshold: 0.80,
    criticalThreshold: 1.80,
    status: 'normal',
    batteryPercent: 91,
    signalDbm: -64,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    rawSignal: 'Transverse Tilt: +0.18° | Longitudinal: -0.05°',
    lat: 23.6092,
    lng: 86.9765,
  },
  {
    id: 'NODE-RAN-TILT-02',
    name: 'River Embankment Inclinometer TILT-02',
    hardwareModel: 'Biaxial MEMS Inclinometer (IP68 Submersible)',
    domain: 'surface',
    type: 'mpu6050_tilt',
    unit: '°',
    location: 'Damodar Right Bank Levee Top (West)',
    depthMeters: 0,
    currentValue: 0.22,
    baselineValue: 0.20,
    warningThreshold: 0.80,
    criticalThreshold: 1.80,
    status: 'normal',
    batteryPercent: 93,
    signalDbm: -67,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    rawSignal: 'Transverse Tilt: +0.22° | Longitudinal: +0.03°',
    lat: 23.6080,
    lng: 86.9690,
  },
  {
    id: 'NODE-RAN-TILT-03',
    name: 'Alluvial Aquitard Borehole Tilt TILT-03',
    hardwareModel: 'Subterranean Deep Casing Tiltmeter',
    domain: 'underground',
    type: 'mpu6050_tilt',
    unit: '°',
    location: 'Aquifer Barrier Sump Horizon (-45m)',
    depthMeters: 45,
    currentValue: 0.29,
    baselineValue: 0.25,
    warningThreshold: 1.50,
    criticalThreshold: 3.00,
    status: 'normal',
    batteryPercent: 88,
    signalDbm: -71,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    rawSignal: 'Shear Flexure Angle: 0.29°',
    lat: 23.6140,
    lng: 86.9735,
  },
  {
    id: 'NODE-RAN-TILT-04',
    name: 'No. 2 Pit Incline Collar Tilt TILT-04',
    hardwareModel: 'Shaft Collar Structural Tiltmeter',
    domain: 'surface',
    type: 'mpu6050_tilt',
    unit: '°',
    location: 'Main Incline Portal Concrete Collar',
    depthMeters: 0,
    currentValue: 0.11,
    baselineValue: 0.10,
    warningThreshold: 0.80,
    criticalThreshold: 1.80,
    status: 'normal',
    batteryPercent: 97,
    signalDbm: -50,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    rawSignal: 'Portal Frame Pitch: +0.11°',
    lat: 23.6225,
    lng: 86.9770,
  },

  // --- 4. Deep Dishergarh Goaf Geophones & Acoustic Emission (4 nodes) ---
  {
    id: 'NODE-RAN-AE-01',
    name: 'Dishergarh Extraction Geophone GEO-01',
    hardwareModel: 'Triaxial Sub-surface Geophone (14Hz GS-20DX)',
    domain: 'underground',
    type: 'mpu6050_vib',
    unit: 'mm/s',
    location: 'Panel D-1 Face Rib, Seam Dishergarh',
    depthMeters: 210,
    currentValue: 0.42,
    baselineValue: 0.35,
    warningThreshold: 5.00,
    criticalThreshold: 12.00,
    status: 'normal',
    batteryPercent: 87,
    signalDbm: -75,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    rawSignal: 'PPV: 0.42 mm/s | Dom Freq: 28.5 Hz',
    lat: 23.6190,
    lng: 86.9675,
  },
  {
    id: 'NODE-RAN-AE-02',
    name: 'Main Haulage Acoustic Emission AE-02',
    hardwareModel: 'High-Frequency Piezoelectric AE Sensor',
    domain: 'underground',
    type: 'mpu6050_vib',
    unit: 'mm/s',
    location: 'Sub-level 3 Main Rail Junction',
    depthMeters: 205,
    currentValue: 0.19,
    baselineValue: 0.15,
    warningThreshold: 5.00,
    criticalThreshold: 12.00,
    status: 'normal',
    batteryPercent: 91,
    signalDbm: -68,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    rawSignal: 'Hit Rate: 3 hits/min | Ringdown Counts: 14',
    lat: 23.6172,
    lng: 86.9755,
  },
  {
    id: 'NODE-RAN-AE-03',
    name: 'Deep Goaf Seismic Geophone GEO-03',
    hardwareModel: 'Borehole Seismic Sensor Array',
    domain: 'underground',
    type: 'mpu6050_vib',
    unit: 'mm/s',
    location: 'Panel D-2 Caved Goaf Void Boundary',
    depthMeters: 220,
    currentValue: 0.68,
    baselineValue: 0.50,
    warningThreshold: 5.00,
    criticalThreshold: 12.00,
    status: 'normal',
    batteryPercent: 83,
    signalDbm: -79,
    zigbeeHops: 3,
    lastUpdated: 'Just now',
    rawSignal: 'Caving Fracture Tremor: 0.68 mm/s @ 18Hz',
    lat: 23.6145,
    lng: 86.9810,
  },
  {
    id: 'NODE-RAN-AE-04',
    name: 'Barrier Protection Geophone GEO-04',
    hardwareModel: 'Triaxial Dynamic Geophone (Ex-d Flameproof)',
    domain: 'underground',
    type: 'mpu6050_vib',
    unit: 'mm/s',
    location: 'Sitarampur Protection Barrier Rib',
    depthMeters: 215,
    currentValue: 0.28,
    baselineValue: 0.22,
    warningThreshold: 5.00,
    criticalThreshold: 12.00,
    status: 'normal',
    batteryPercent: 89,
    signalDbm: -73,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    rawSignal: 'Barrier PPV: 0.28 mm/s',
    lat: 23.6238,
    lng: 86.9710,
  },

  // --- 5. Tailgate Catalytic Methane Gas Sensors (2 nodes) ---
  {
    id: 'NODE-RAN-GAS-01',
    name: 'Dishergarh Return Airway CH4 GAS-01',
    hardwareModel: 'MQ-4 Catalytic Methane Sensor (DGMS Certified)',
    domain: 'underground',
    type: 'mq4_gas',
    unit: '% LEL',
    location: 'Panel D-1 Return Bleeder Roadway',
    depthMeters: 210,
    currentValue: 0.26,
    baselineValue: 0.20,
    warningThreshold: 0.80,
    criticalThreshold: 1.25,
    status: 'normal',
    batteryPercent: 94,
    signalDbm: -69,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    rawSignal: 'Analog Rs/Ro: 13.9kΩ (~130 ppm CH4)',
    lat: 23.6178,
    lng: 86.9660,
  },
  {
    id: 'NODE-RAN-GAS-02',
    name: 'Goaf Perimeter Bleeder CH4 GAS-02',
    hardwareModel: 'MQ-4 Catalytic Methane Sensor (DGMS Certified)',
    domain: 'underground',
    type: 'mq4_gas',
    unit: '% LEL',
    location: 'Panel D-2 Tailgate Degasification Pipe',
    depthMeters: 215,
    currentValue: 0.32,
    baselineValue: 0.25,
    warningThreshold: 0.80,
    criticalThreshold: 1.25,
    status: 'normal',
    batteryPercent: 90,
    signalDbm: -74,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    rawSignal: 'Analog Rs/Ro: 11.5kΩ (~160 ppm CH4)',
    lat: 23.6135,
    lng: 86.9795,
  },
];

// =============================================================================
// KARANPURA COALFIELDS (JHARKHAND) — DEDICATED 14-NODE SENSOR FLEET
// =============================================================================
export const KARANPURA_SENSOR_NODES: SensorNode[] = [
  {
    id: 'NODE-KAR-EXT-01',
    name: 'Karanpura Basin Extensometer EXT-01',
    hardwareModel: 'Linear Borehole Potentiometer',
    domain: 'surface',
    type: 'linear_pot',
    unit: 'mm',
    location: 'North Karanpura Overburden Bench',
    depthMeters: 0,
    currentValue: 1.15,
    baselineValue: 1.10,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 93,
    signalDbm: -60,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.8540,
    lng: 85.2810,
  },
  {
    id: 'NODE-KAR-EXT-02',
    name: 'Karharbari Seam Extensometer EXT-02',
    hardwareModel: 'Multi-Anchor Borehole Extensometer',
    domain: 'underground',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Seam II Depillaring Face (-195m RL)',
    depthMeters: 195,
    currentValue: 2.30,
    baselineValue: 2.10,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 90,
    signalDbm: -68,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    lat: 23.8495,
    lng: 85.2870,
  },
  {
    id: 'NODE-KAR-GNSS-01',
    name: 'Karanpura Base GNSS Station',
    hardwareModel: 'High-Precision GNSS Geodetic Unit',
    domain: 'surface',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Pithead Administrative Tower',
    depthMeters: 0,
    currentValue: 0.95,
    baselineValue: 0.90,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 98,
    signalDbm: -52,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.8512,
    lng: 85.2845,
  },
  {
    id: 'NODE-KAR-GNSS-02',
    name: 'InSAR Radar Corner Reflector CCR-01',
    hardwareModel: 'Trihedral Radar Reflector',
    domain: 'surface',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Opencast Highwall Crest',
    depthMeters: 0,
    currentValue: 1.80,
    baselineValue: 1.70,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 96,
    signalDbm: -54,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.8565,
    lng: 85.2890,
  },
  {
    id: 'NODE-KAR-TILT-01',
    name: 'Highwall Slope Tiltmeter TILT-01',
    hardwareModel: 'Biaxial MEMS Inclinometer',
    domain: 'surface',
    type: 'mpu6050_tilt',
    unit: '°',
    location: 'West Highwall Crest Bench',
    depthMeters: 0,
    currentValue: 0.16,
    baselineValue: 0.14,
    warningThreshold: 0.80,
    criticalThreshold: 1.80,
    status: 'normal',
    batteryPercent: 91,
    signalDbm: -64,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.8530,
    lng: 85.2785,
  },
  {
    id: 'NODE-KAR-TILT-02',
    name: 'Haul Road Slope Inclinometer TILT-02',
    hardwareModel: 'Biaxial MEMS Inclinometer',
    domain: 'surface',
    type: 'mpu6050_tilt',
    unit: '°',
    location: 'Main Haul Road Ramp 4',
    depthMeters: 0,
    currentValue: 0.12,
    baselineValue: 0.10,
    warningThreshold: 0.80,
    criticalThreshold: 1.80,
    status: 'normal',
    batteryPercent: 95,
    signalDbm: -57,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.8475,
    lng: 85.2830,
  },
  {
    id: 'NODE-KAR-TILT-03',
    name: 'Underground Roof Inclinometer TILT-03',
    hardwareModel: 'Sub-Level Strata Tiltmeter',
    domain: 'underground',
    type: 'mpu6050_tilt',
    unit: '°',
    location: 'Sub-level Gallery 2 West',
    depthMeters: 190,
    currentValue: 0.24,
    baselineValue: 0.20,
    warningThreshold: 1.50,
    criticalThreshold: 3.00,
    status: 'normal',
    batteryPercent: 88,
    signalDbm: -72,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    lat: 23.8500,
    lng: 85.2815,
  },
  {
    id: 'NODE-KAR-AE-01',
    name: 'Karharbari Geophone Station GEO-01',
    hardwareModel: '14Hz Triaxial Geophone',
    domain: 'underground',
    type: 'mpu6050_vib',
    unit: 'mm/s',
    location: 'Panel 1 Extraction Edge',
    depthMeters: 195,
    currentValue: 0.35,
    baselineValue: 0.30,
    warningThreshold: 5.00,
    criticalThreshold: 12.00,
    status: 'normal',
    batteryPercent: 86,
    signalDbm: -76,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    lat: 23.8488,
    lng: 85.2885,
  },
  {
    id: 'NODE-KAR-AE-02',
    name: 'Main Sump Dynamic Geophone GEO-02',
    hardwareModel: 'Borehole Seismic Sensor',
    domain: 'underground',
    type: 'mpu6050_vib',
    unit: 'mm/s',
    location: 'Main Sump Chamber',
    depthMeters: 200,
    currentValue: 0.22,
    baselineValue: 0.18,
    warningThreshold: 5.00,
    criticalThreshold: 12.00,
    status: 'normal',
    batteryPercent: 89,
    signalDbm: -70,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    lat: 23.8525,
    lng: 85.2910,
  },
  {
    id: 'NODE-KAR-AE-03',
    name: 'Barrier Acoustic Emission AE-03',
    hardwareModel: 'High-Frequency AE Sensor',
    domain: 'underground',
    type: 'mpu6050_vib',
    unit: 'mm/s',
    location: 'Safety Barrier Pillar B-4',
    depthMeters: 192,
    currentValue: 0.15,
    baselineValue: 0.12,
    warningThreshold: 5.00,
    criticalThreshold: 12.00,
    status: 'normal',
    batteryPercent: 92,
    signalDbm: -67,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.8548,
    lng: 85.2855,
  },
  {
    id: 'NODE-KAR-GAS-01',
    name: 'Panel 1 Bleeder CH4 Sensor',
    hardwareModel: 'MQ-4 Catalytic Methane Sensor',
    domain: 'underground',
    type: 'mq4_gas',
    unit: '% LEL',
    location: 'Return Airway Split 1',
    depthMeters: 195,
    currentValue: 0.22,
    baselineValue: 0.18,
    warningThreshold: 0.80,
    criticalThreshold: 1.25,
    status: 'normal',
    batteryPercent: 93,
    signalDbm: -71,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    lat: 23.8490,
    lng: 85.2800,
  },
  {
    id: 'NODE-KAR-GAS-02',
    name: 'Goaf Perimeter Gas Monitor',
    hardwareModel: 'MQ-4 Catalytic Methane Sensor',
    domain: 'underground',
    type: 'mq4_gas',
    unit: '% LEL',
    location: 'Karharbari Goaf Bleeder',
    depthMeters: 198,
    currentValue: 0.28,
    baselineValue: 0.22,
    warningThreshold: 0.80,
    criticalThreshold: 1.25,
    status: 'normal',
    batteryPercent: 91,
    signalDbm: -74,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    lat: 23.8470,
    lng: 85.2860,
  },
  {
    id: 'NODE-KAR-STR-01',
    name: 'Karharbari Barrier Strain BF350-01',
    hardwareModel: 'BF350 Strain Gauge + HX711',
    domain: 'underground',
    type: 'bf350_strain',
    unit: 'µε',
    location: 'Pillar K-04 Core (-195m RL)',
    depthMeters: 195,
    currentValue: 135.0,
    baselineValue: 125.0,
    warningThreshold: 350.0,
    criticalThreshold: 600.0,
    status: 'normal',
    batteryPercent: 94,
    signalDbm: -66,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.8518,
    lng: 85.2875,
  },
  {
    id: 'NODE-KAR-STR-02',
    name: 'Karharbari Depillaring Strain BF350-02',
    hardwareModel: 'BF350 Strain Gauge + HX711',
    domain: 'underground',
    type: 'bf350_strain',
    unit: 'µε',
    location: 'Pillar K-08 Flank Rib',
    depthMeters: 195,
    currentValue: 152.0,
    baselineValue: 140.0,
    warningThreshold: 350.0,
    criticalThreshold: 600.0,
    status: 'normal',
    batteryPercent: 89,
    signalDbm: -73,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    lat: 23.8482,
    lng: 85.2840,
  },
];

// =============================================================================
// KORBA COALFIELD (CHHATTISGARH / SECL) — DEDICATED 16-NODE SENSOR FLEET
// =============================================================================
export const KORBA_SENSOR_NODES: SensorNode[] = [
  {
    id: 'NODE-KOR-EXT-01',
    name: 'Kusmunda Highwall Extensometer EXT-01',
    hardwareModel: 'Linear Slide Potentiometer 100mm',
    domain: 'surface',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Kusmunda Opencast North Crest',
    depthMeters: 0,
    currentValue: 1.40,
    baselineValue: 1.30,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 95,
    signalDbm: -56,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 22.3630,
    lng: 82.7460,
  },
  {
    id: 'NODE-KOR-EXT-02',
    name: 'Hasdeo River Buffer Extensometer EXT-02',
    hardwareModel: 'Multi-Anchor Ground Extensometer',
    domain: 'surface',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Hasdeo River Embankment Zone',
    depthMeters: 12,
    currentValue: 1.10,
    baselineValue: 1.05,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 93,
    signalDbm: -61,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 22.3555,
    lng: 82.7480,
  },
  {
    id: 'NODE-KOR-EXT-03',
    name: 'Kusmunda Deep Seam Extensometer EXT-03',
    hardwareModel: 'Subterranean LVDT Borehole Extensometer',
    domain: 'underground',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Lower Kusmunda Seam (-160m RL)',
    depthMeters: 160,
    currentValue: 2.80,
    baselineValue: 2.50,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 88,
    signalDbm: -72,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    lat: 22.3585,
    lng: 82.7540,
  },
  {
    id: 'NODE-KOR-GNSS-01',
    name: 'Korba SECL Base GNSS Station',
    hardwareModel: 'High-Precision Geodetic GNSS',
    domain: 'surface',
    type: 'linear_pot',
    unit: 'mm',
    location: 'SECL Gevra-Kusmunda Area HQ',
    depthMeters: 0,
    currentValue: 0.88,
    baselineValue: 0.85,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 99,
    signalDbm: -49,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 22.3595,
    lng: 82.7501,
  },
  {
    id: 'NODE-KOR-GNSS-02',
    name: 'InSAR Radar Reflector CCR-01',
    hardwareModel: '1.2m Corner Cube InSAR Transponder',
    domain: 'surface',
    type: 'linear_pot',
    unit: 'mm',
    location: 'East Dump Overburden Slope',
    depthMeters: 0,
    currentValue: 2.10,
    baselineValue: 2.00,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 97,
    signalDbm: -53,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 22.3650,
    lng: 82.7535,
  },
  {
    id: 'NODE-KOR-GNSS-03',
    name: 'InSAR Radar Reflector CCR-02',
    hardwareModel: '1.2m Corner Cube InSAR Transponder',
    domain: 'surface',
    type: 'linear_pot',
    unit: 'mm',
    location: 'South Barrier Flood Levee',
    depthMeters: 0,
    currentValue: 1.25,
    baselineValue: 1.20,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 96,
    signalDbm: -58,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 22.3530,
    lng: 82.7515,
  },
  {
    id: 'NODE-KOR-TILT-01',
    name: 'Overburden Dump Tiltmeter TILT-01',
    hardwareModel: 'Biaxial MEMS Inclinometer',
    domain: 'surface',
    type: 'mpu6050_tilt',
    unit: '°',
    location: 'OB Dump Sector 4 Crest',
    depthMeters: 0,
    currentValue: 0.21,
    baselineValue: 0.18,
    warningThreshold: 0.80,
    criticalThreshold: 1.80,
    status: 'normal',
    batteryPercent: 92,
    signalDbm: -63,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 22.3645,
    lng: 82.7485,
  },
  {
    id: 'NODE-KOR-TILT-02',
    name: 'Pit Bench Slope Tiltmeter TILT-02',
    hardwareModel: 'Biaxial MEMS Inclinometer',
    domain: 'surface',
    type: 'mpu6050_tilt',
    unit: '°',
    location: 'Bench B-7 Haulage Approach',
    depthMeters: 0,
    currentValue: 0.15,
    baselineValue: 0.12,
    warningThreshold: 0.80,
    criticalThreshold: 1.80,
    status: 'normal',
    batteryPercent: 94,
    signalDbm: -59,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 22.3610,
    lng: 82.7440,
  },
  {
    id: 'NODE-KOR-TILT-03',
    name: 'Underground Incline Tiltmeter TILT-03',
    hardwareModel: 'Subterranean IMU Inclinometer',
    domain: 'underground',
    type: 'mpu6050_tilt',
    unit: '°',
    location: 'Main Incline Portal Strata (-80m)',
    depthMeters: 80,
    currentValue: 0.19,
    baselineValue: 0.16,
    warningThreshold: 1.50,
    criticalThreshold: 3.00,
    status: 'normal',
    batteryPercent: 90,
    signalDbm: -69,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    lat: 22.3570,
    lng: 82.7520,
  },
  {
    id: 'NODE-KOR-TILT-04',
    name: 'Hasdeo Bridge Abutment Tilt TILT-04',
    hardwareModel: 'Bridge & Levee Inclinometer',
    domain: 'surface',
    type: 'mpu6050_tilt',
    unit: '°',
    location: 'Hasdeo Heavy Haul Rail Bridge',
    depthMeters: 0,
    currentValue: 0.09,
    baselineValue: 0.08,
    warningThreshold: 0.80,
    criticalThreshold: 1.80,
    status: 'normal',
    batteryPercent: 98,
    signalDbm: -51,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 22.3540,
    lng: 82.7455,
  },
  {
    id: 'NODE-KOR-AE-01',
    name: 'Lower Kusmunda Geophone GEO-01',
    hardwareModel: 'Triaxial Sub-surface Geophone',
    domain: 'underground',
    type: 'mpu6050_vib',
    unit: 'mm/s',
    location: 'Lower Kusmunda Face 3 (-160m RL)',
    depthMeters: 160,
    currentValue: 0.38,
    baselineValue: 0.32,
    warningThreshold: 5.00,
    criticalThreshold: 12.00,
    status: 'normal',
    batteryPercent: 87,
    signalDbm: -75,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    lat: 22.3600,
    lng: 82.7555,
  },
  {
    id: 'NODE-KOR-AE-02',
    name: 'Strata Acoustic Emission AE-02',
    hardwareModel: 'High-Frequency AE Sensor',
    domain: 'underground',
    type: 'mpu6050_vib',
    unit: 'mm/s',
    location: 'Lower Seam Main Junction',
    depthMeters: 160,
    currentValue: 0.21,
    baselineValue: 0.17,
    warningThreshold: 5.00,
    criticalThreshold: 12.00,
    status: 'normal',
    batteryPercent: 89,
    signalDbm: -71,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    lat: 22.3575,
    lng: 82.7490,
  },
  {
    id: 'NODE-KOR-AE-03',
    name: 'Highwall Blast Vibration GEO-03',
    hardwareModel: 'Surface Seismic Blast Monitor',
    domain: 'surface',
    type: 'mpu6050_vib',
    unit: 'mm/s',
    location: 'North Highwall Perimeter Post',
    depthMeters: 0,
    currentValue: 0.45,
    baselineValue: 0.30,
    warningThreshold: 5.00,
    criticalThreshold: 12.00,
    status: 'normal',
    batteryPercent: 93,
    signalDbm: -62,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 22.3660,
    lng: 82.7470,
  },
  {
    id: 'NODE-KOR-GAS-01',
    name: 'Lower Kusmunda Return CH4 Sensor',
    hardwareModel: 'MQ-4 Catalytic Methane Sensor',
    domain: 'underground',
    type: 'mq4_gas',
    unit: '% LEL',
    location: 'Ventilation Shaft Return Fan Base',
    depthMeters: 160,
    currentValue: 0.19,
    baselineValue: 0.15,
    warningThreshold: 0.80,
    criticalThreshold: 1.25,
    status: 'normal',
    batteryPercent: 94,
    signalDbm: -68,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 22.3580,
    lng: 82.7565,
  },
  {
    id: 'NODE-KOR-STR-01',
    name: 'Kusmunda Pillar Strain BF350-01',
    hardwareModel: 'BF350 Strain Gauge + HX711',
    domain: 'underground',
    type: 'bf350_strain',
    unit: 'µε',
    location: 'Pillar KR-05 Core (-160m RL)',
    depthMeters: 160,
    currentValue: 122.0,
    baselineValue: 115.0,
    warningThreshold: 350.0,
    criticalThreshold: 600.0,
    status: 'normal',
    batteryPercent: 91,
    signalDbm: -70,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    lat: 22.3615,
    lng: 82.7525,
  },
  {
    id: 'NODE-KOR-STR-02',
    name: 'Kusmunda Barrier Strain BF350-02',
    hardwareModel: 'BF350 Strain Gauge + HX711',
    domain: 'underground',
    type: 'bf350_strain',
    unit: 'µε',
    location: 'Barrier Pillar KR-12',
    depthMeters: 160,
    currentValue: 138.0,
    baselineValue: 128.0,
    warningThreshold: 350.0,
    criticalThreshold: 600.0,
    status: 'normal',
    batteryPercent: 88,
    signalDbm: -74,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    lat: 22.3560,
    lng: 82.7545,
  },
];

// =============================================================================
// JHARIA COLLIERY (BLOCK IV) — 32 SENSOR FLEET (16 SURFACE + 16 UNDERGROUND)
// =============================================================================
export const JHARIA_FULL_SENSOR_NODES: SensorNode[] = [
  // 16 Surface Array Nodes
  {
    id: 'NODE-SF-POT-01',
    name: 'Surface Subsidence Potentiometer POT-01',
    hardwareModel: 'Linear Potentiometer 50mm Travel',
    domain: 'surface',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Pithead Subsidence Monument SF-01',
    depthMeters: 0,
    currentValue: 1.25,
    baselineValue: 1.20,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 97,
    signalDbm: -54,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    rawSignal: 'ADC 12-bit: 102/4095 (0.082V)',
    lat: 23.7435,
    lng: 86.4175,
  },
  {
    id: 'NODE-SF-POT-02',
    name: 'Surface Subsidence Potentiometer POT-02',
    hardwareModel: 'Linear Potentiometer 50mm Travel',
    domain: 'surface',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Monument SF-02 (Sag Zone Perimeter)',
    depthMeters: 0,
    currentValue: 2.10,
    baselineValue: 1.90,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 95,
    signalDbm: -58,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.7442,
    lng: 86.4162,
  },
  {
    id: 'NODE-SF-POT-03',
    name: 'Surface Fissure Potentiometer POT-03',
    hardwareModel: 'Linear Ground Displacement Potentiometer',
    domain: 'surface',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Monument SF-03 (North Crown)',
    depthMeters: 0,
    currentValue: 1.80,
    baselineValue: 1.70,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 94,
    signalDbm: -56,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.7455,
    lng: 86.4190,
  },
  {
    id: 'NODE-SF-POT-04',
    name: 'Surface Ground Potentiometer POT-04',
    hardwareModel: 'Linear Ground Displacement Potentiometer',
    domain: 'surface',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Monument SF-04 (East Flank)',
    depthMeters: 0,
    currentValue: 1.45,
    baselineValue: 1.40,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 96,
    signalDbm: -52,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.7410,
    lng: 86.4220,
  },
  {
    id: 'NODE-SF-MPU-01',
    name: 'Surface Slope Inclinometer MPU-01',
    hardwareModel: 'MPU-6050 6-Axis IMU (I2C 0x68)',
    domain: 'surface',
    type: 'mpu6050_tilt',
    unit: '°',
    location: 'Ground Monument Station SF-01',
    depthMeters: 0,
    currentValue: 0.14,
    baselineValue: 0.12,
    warningThreshold: 0.80,
    criticalThreshold: 1.80,
    status: 'normal',
    batteryPercent: 95,
    signalDbm: -56,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    rawSignal: 'Pitch: +0.14° | Roll: -0.06°',
    lat: 23.7430,
    lng: 86.4180,
  },
  {
    id: 'NODE-SF-MPU-02',
    name: 'Surface Ground Vibration MPU-02',
    hardwareModel: 'MPU-6050 6-Axis IMU (I2C 0x69)',
    domain: 'surface',
    type: 'mpu6050_vib',
    unit: 'mm/s',
    location: 'Perimeter Surface Array SF-02',
    depthMeters: 0,
    currentValue: 0.08,
    baselineValue: 0.05,
    warningThreshold: 2.50,
    criticalThreshold: 6.00,
    status: 'normal',
    batteryPercent: 91,
    signalDbm: -63,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    rawSignal: 'RMS Accel: 0.008g (PPV: 0.08 mm/s)',
    lat: 23.7415,
    lng: 86.4168,
  },
  {
    id: 'NODE-SF-MPU-03',
    name: 'Surface Slope Inclinometer MPU-03',
    hardwareModel: 'MPU-6050 6-Axis IMU',
    domain: 'surface',
    type: 'mpu6050_tilt',
    unit: '°',
    location: 'Ground Monument Station SF-03',
    depthMeters: 0,
    currentValue: 0.19,
    baselineValue: 0.16,
    warningThreshold: 0.80,
    criticalThreshold: 1.80,
    status: 'normal',
    batteryPercent: 93,
    signalDbm: -59,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.7448,
    lng: 86.4155,
  },
  {
    id: 'NODE-SF-MPU-04',
    name: 'Surface Ground Motion MPU-04',
    hardwareModel: 'MPU-6050 6-Axis IMU',
    domain: 'surface',
    type: 'mpu6050_vib',
    unit: 'mm/s',
    location: 'Perimeter Surface Array SF-04',
    depthMeters: 0,
    currentValue: 0.12,
    baselineValue: 0.08,
    warningThreshold: 2.50,
    criticalThreshold: 6.00,
    status: 'normal',
    batteryPercent: 92,
    signalDbm: -61,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.7405,
    lng: 86.4205,
  },
  {
    id: 'NODE-SF-GNSS-01',
    name: 'InSAR Corner Reflector CCR-JH-01',
    hardwareModel: 'Corner Cube Radar Reflector',
    domain: 'surface',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Block IV Extraction Ridge',
    depthMeters: 0,
    currentValue: 2.45,
    baselineValue: 2.30,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 98,
    signalDbm: -50,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.7440,
    lng: 86.4170,
  },
  {
    id: 'NODE-SF-GNSS-02',
    name: 'InSAR Corner Reflector CCR-JH-02',
    hardwareModel: 'Corner Cube Radar Reflector',
    domain: 'surface',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Seam XII Abutment Crest',
    depthMeters: 0,
    currentValue: 1.60,
    baselineValue: 1.50,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 97,
    signalDbm: -53,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.7412,
    lng: 86.4215,
  },
  {
    id: 'NODE-SF-SURF-07',
    name: 'Surface Settlement Pin SF-07',
    hardwareModel: 'Precision Linear Sensor',
    domain: 'surface',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Jharia Colliery North Gate',
    depthMeters: 0,
    currentValue: 0.95,
    baselineValue: 0.90,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 96,
    signalDbm: -55,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.7460,
    lng: 86.4178,
  },
  {
    id: 'NODE-SF-SURF-08',
    name: 'Surface Settlement Pin SF-08',
    hardwareModel: 'Precision Linear Sensor',
    domain: 'surface',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Haul Road Junction Monument',
    depthMeters: 0,
    currentValue: 1.10,
    baselineValue: 1.05,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 95,
    signalDbm: -57,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.7398,
    lng: 86.4185,
  },
  {
    id: 'NODE-SF-SURF-09',
    name: 'Surface Inclinometer MPU-05',
    hardwareModel: 'MPU-6050 6-Axis IMU',
    domain: 'surface',
    type: 'mpu6050_tilt',
    unit: '°',
    location: 'West Waste Dump Bench',
    depthMeters: 0,
    currentValue: 0.16,
    baselineValue: 0.14,
    warningThreshold: 0.80,
    criticalThreshold: 1.80,
    status: 'normal',
    batteryPercent: 93,
    signalDbm: -60,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.7432,
    lng: 86.4140,
  },
  {
    id: 'NODE-SF-SURF-10',
    name: 'Surface Inclinometer MPU-06',
    hardwareModel: 'MPU-6050 6-Axis IMU',
    domain: 'surface',
    type: 'mpu6050_tilt',
    unit: '°',
    location: 'South Barrier Bench',
    depthMeters: 0,
    currentValue: 0.11,
    baselineValue: 0.10,
    warningThreshold: 0.80,
    criticalThreshold: 1.80,
    status: 'normal',
    batteryPercent: 94,
    signalDbm: -58,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.7388,
    lng: 86.4210,
  },
  {
    id: 'NODE-SF-SURF-11',
    name: 'Surface Vibration MPU-07',
    hardwareModel: 'MPU-6050 6-Axis IMU',
    domain: 'surface',
    type: 'mpu6050_vib',
    unit: 'mm/s',
    location: 'East Ventilation Fan Collar',
    depthMeters: 0,
    currentValue: 0.15,
    baselineValue: 0.10,
    warningThreshold: 2.50,
    criticalThreshold: 6.00,
    status: 'normal',
    batteryPercent: 92,
    signalDbm: -62,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.7420,
    lng: 86.4235,
  },
  {
    id: 'NODE-SF-SURF-12',
    name: 'Surface Settlement Pin SF-12',
    hardwareModel: 'Precision Linear Sensor',
    domain: 'surface',
    type: 'linear_pot',
    unit: 'mm',
    location: 'Central Substation Foundation',
    depthMeters: 0,
    currentValue: 0.78,
    baselineValue: 0.75,
    warningThreshold: 10.0,
    criticalThreshold: 25.0,
    status: 'normal',
    batteryPercent: 99,
    signalDbm: -48,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.7425,
    lng: 86.4195,
  },

  // 16 Underground Seam XII Nodes (P-01 to P-16 matching underground grid)
  {
    id: 'NODE-UG-BF350-01',
    name: 'Pillar Core Strain BF350-01',
    hardwareModel: 'BF350 Strain Gauge + HX711 24-bit ADC',
    domain: 'underground',
    type: 'bf350_strain',
    unit: 'µε',
    location: 'Pillar P-06 Core, Seam XII',
    depthMeters: 248,
    currentValue: 142.5,
    baselineValue: 135.0,
    warningThreshold: 350.0,
    criticalThreshold: 600.0,
    status: 'normal',
    batteryPercent: 92,
    signalDbm: -68,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    rawSignal: 'HX711 24-bit: 2,992,500 counts (21.0 c/µε)',
    lat: 23.7438,
    lng: 86.4168,
  },
  {
    id: 'NODE-UG-BF350-02',
    name: 'Depillaring Flank Strain BF350-02',
    hardwareModel: 'BF350 Strain Gauge + HX711 24-bit ADC',
    domain: 'underground',
    type: 'bf350_strain',
    unit: 'µε',
    location: 'Pillar P-11 Rib, Extraction Face',
    depthMeters: 256,
    currentValue: 168.2,
    baselineValue: 155.0,
    warningThreshold: 350.0,
    criticalThreshold: 600.0,
    status: 'normal',
    batteryPercent: 88,
    signalDbm: -74,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    rawSignal: 'HX711 24-bit: 3,532,200 counts (21.0 c/µε)',
    lat: 23.7441,
    lng: 86.4172,
  },
  {
    id: 'NODE-UG-BF350-03',
    name: 'Pillar P-10 Winze Strain BF350-03',
    hardwareModel: 'BF350 Strain Gauge + HX711',
    domain: 'underground',
    type: 'bf350_strain',
    unit: 'µε',
    location: 'Pillar P-10 Deep Winze (-255m RL)',
    depthMeters: 255,
    currentValue: 155.0,
    baselineValue: 145.0,
    warningThreshold: 350.0,
    criticalThreshold: 600.0,
    status: 'normal',
    batteryPercent: 90,
    signalDbm: -70,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    lat: 23.7445,
    lng: 86.4165,
  },
  {
    id: 'NODE-UG-BF350-04',
    name: 'Pillar P-07 Panel Strain BF350-04',
    hardwareModel: 'BF350 Strain Gauge + HX711',
    domain: 'underground',
    type: 'bf350_strain',
    unit: 'µε',
    location: 'Pillar P-07 Central Panel (-250m RL)',
    depthMeters: 250,
    currentValue: 138.0,
    baselineValue: 130.0,
    warningThreshold: 350.0,
    criticalThreshold: 600.0,
    status: 'normal',
    batteryPercent: 91,
    signalDbm: -69,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.7430,
    lng: 86.4182,
  },
  {
    id: 'NODE-UG-MPU-01',
    name: 'Roof Strata Inclinometer MPU-01',
    hardwareModel: 'MPU-6050 6-Axis IMU (Subterranean Ex-ia)',
    domain: 'underground',
    type: 'mpu6050_tilt',
    unit: '°',
    location: 'Gallery 4-East Roof Anchor, Seam XII',
    depthMeters: 245,
    currentValue: 0.36,
    baselineValue: 0.30,
    warningThreshold: 1.50,
    criticalThreshold: 3.00,
    status: 'normal',
    batteryPercent: 94,
    signalDbm: -66,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    rawSignal: 'Roof Delamination Pitch: +0.36°',
    lat: 23.7428,
    lng: 86.4190,
  },
  {
    id: 'NODE-UG-MPU-02',
    name: 'Strata Shock Vibration MPU-02',
    hardwareModel: 'MPU-6050 6-Axis IMU (Dynamic Geophone)',
    domain: 'underground',
    type: 'mpu6050_vib',
    unit: 'mm/s',
    location: 'Pillar P-10 Deep Winze Chamber',
    depthMeters: 260,
    currentValue: 0.22,
    baselineValue: 0.15,
    warningThreshold: 5.00,
    criticalThreshold: 12.00,
    status: 'normal',
    batteryPercent: 84,
    signalDbm: -78,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    rawSignal: 'PPV Peak: 0.22 mm/s @ 32Hz',
    lat: 23.7446,
    lng: 86.4160,
  },
  {
    id: 'NODE-UG-MPU-03',
    name: 'Extraction Face Geophone MPU-03',
    hardwareModel: 'MPU-6050 6-Axis IMU',
    domain: 'underground',
    type: 'mpu6050_vib',
    unit: 'mm/s',
    location: 'Pillar P-11 Depillaring Goaf Edge',
    depthMeters: 256,
    currentValue: 0.34,
    baselineValue: 0.25,
    warningThreshold: 5.00,
    criticalThreshold: 12.00,
    status: 'normal',
    batteryPercent: 86,
    signalDbm: -76,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    lat: 23.7442,
    lng: 86.4175,
  },
  {
    id: 'NODE-UG-MPU-04',
    name: 'Gallery 2 Inclinometer MPU-04',
    hardwareModel: 'MPU-6050 6-Axis IMU',
    domain: 'underground',
    type: 'mpu6050_tilt',
    unit: '°',
    location: 'Main Haulage Roof Crosscut',
    depthMeters: 244,
    currentValue: 0.28,
    baselineValue: 0.25,
    warningThreshold: 1.50,
    criticalThreshold: 3.00,
    status: 'normal',
    batteryPercent: 92,
    signalDbm: -67,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.7420,
    lng: 86.4175,
  },
  {
    id: 'NODE-UG-MQ4-01',
    name: 'Tailgate Methane Gas Sensor MQ4-01',
    hardwareModel: 'MQ-4 Catalytic Methane (CH4) Sensor',
    domain: 'underground',
    type: 'mq4_gas',
    unit: '% LEL',
    location: 'Tailgate Return Airway, Seam XII',
    depthMeters: 252,
    currentValue: 0.22,
    baselineValue: 0.15,
    warningThreshold: 0.80,
    criticalThreshold: 1.25,
    status: 'normal',
    batteryPercent: 90,
    signalDbm: -70,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    rawSignal: 'Analog Rs/Ro: 14.8kΩ (~110 ppm CH4)',
    lat: 23.7436,
    lng: 86.4160,
  },
  {
    id: 'NODE-UG-MQ4-02',
    name: 'Goaf Perimeter Methane MQ4-02',
    hardwareModel: 'MQ-4 Catalytic Methane (CH4) Sensor',
    domain: 'underground',
    type: 'mq4_gas',
    unit: '% LEL',
    location: 'Goaf Bleeder Channel North',
    depthMeters: 240,
    currentValue: 0.28,
    baselineValue: 0.20,
    warningThreshold: 0.80,
    criticalThreshold: 1.25,
    status: 'normal',
    batteryPercent: 96,
    signalDbm: -62,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    rawSignal: 'Analog Rs/Ro: 12.2kΩ (~140 ppm CH4)',
    lat: 23.7450,
    lng: 86.4170,
  },
  {
    id: 'NODE-UG-MQ4-03',
    name: 'Panel Return Airway Methane MQ4-03',
    hardwareModel: 'MQ-4 Catalytic Methane Sensor',
    domain: 'underground',
    type: 'mq4_gas',
    unit: '% LEL',
    location: 'Airway Split East (-245m RL)',
    depthMeters: 245,
    currentValue: 0.18,
    baselineValue: 0.14,
    warningThreshold: 0.80,
    criticalThreshold: 1.25,
    status: 'normal',
    batteryPercent: 93,
    signalDbm: -68,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.7415,
    lng: 86.4210,
  },
  {
    id: 'NODE-UG-MQ4-04',
    name: 'Shaft Inset Methane Monitor MQ4-04',
    hardwareModel: 'MQ-4 Catalytic Methane Sensor',
    domain: 'underground',
    type: 'mq4_gas',
    unit: '% LEL',
    location: 'Shaft No. 1 Inset Station',
    depthMeters: 240,
    currentValue: 0.12,
    baselineValue: 0.10,
    warningThreshold: 0.80,
    criticalThreshold: 1.25,
    status: 'normal',
    batteryPercent: 98,
    signalDbm: -52,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.7422,
    lng: 86.4188,
  },
  {
    id: 'NODE-UG-STR-05',
    name: 'Pillar P-01 Shaft Strain BF350-05',
    hardwareModel: 'BF350 Strain Gauge + HX711',
    domain: 'underground',
    type: 'bf350_strain',
    unit: 'µε',
    location: 'Pillar P-01 Shaft Pillar (-240m RL)',
    depthMeters: 240,
    currentValue: 110.0,
    baselineValue: 105.0,
    warningThreshold: 350.0,
    criticalThreshold: 600.0,
    status: 'normal',
    batteryPercent: 97,
    signalDbm: -55,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.7418,
    lng: 86.4180,
  },
  {
    id: 'NODE-UG-STR-06',
    name: 'Pillar P-05 Junction Strain BF350-06',
    hardwareModel: 'BF350 Strain Gauge + HX711',
    domain: 'underground',
    type: 'bf350_strain',
    unit: 'µε',
    location: 'Pillar P-05 Junction 2 (-246m RL)',
    depthMeters: 246,
    currentValue: 128.0,
    baselineValue: 122.0,
    warningThreshold: 350.0,
    criticalThreshold: 600.0,
    status: 'normal',
    batteryPercent: 95,
    signalDbm: -59,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.7432,
    lng: 86.4172,
  },
  {
    id: 'NODE-UG-STR-07',
    name: 'Pillar P-09 Goaf Strain BF350-07',
    hardwareModel: 'BF350 Strain Gauge + HX711',
    domain: 'underground',
    type: 'bf350_strain',
    unit: 'µε',
    location: 'Pillar P-09 Barrier Rib (-252m RL)',
    depthMeters: 252,
    currentValue: 145.0,
    baselineValue: 138.0,
    warningThreshold: 350.0,
    criticalThreshold: 600.0,
    status: 'normal',
    batteryPercent: 91,
    signalDbm: -67,
    zigbeeHops: 2,
    lastUpdated: 'Just now',
    lat: 23.7444,
    lng: 86.4158,
  },
  {
    id: 'NODE-UG-STR-08',
    name: 'Pillar P-16 Boundary Strain BF350-08',
    hardwareModel: 'BF350 Strain Gauge + HX711',
    domain: 'underground',
    type: 'bf350_strain',
    unit: 'µε',
    location: 'Pillar P-16 Boundary Wall (-260m RL)',
    depthMeters: 260,
    currentValue: 115.0,
    baselineValue: 110.0,
    warningThreshold: 350.0,
    criticalThreshold: 600.0,
    status: 'normal',
    batteryPercent: 96,
    signalDbm: -58,
    zigbeeHops: 1,
    lastUpdated: 'Just now',
    lat: 23.7408,
    lng: 86.4225,
  },
];

export function getSensorsForCoalfield(coalfieldId: string): SensorNode[] {
  switch (coalfieldId) {
    case 'raniganj-sector-2':
      return RANIGANJ_SENSOR_NODES;
    case 'karanpura-block-1':
      return KARANPURA_SENSOR_NODES;
    case 'korba-secl':
      return KORBA_SENSOR_NODES;
    case 'jharia-block-4':
    default:
      return JHARIA_FULL_SENSOR_NODES;
  }
}

